### ISSUE TITLE
Not Unity-ready

### ISSUE THREAD

**Issue by CindyVR** [microsoft/Microsoft-Rocketbox#1]
Is there a tutorial, guide, or script to make these models Unity-ready, without having to fix hundreds of bones hierarchies?  Or is there a set available that is Unity-ready?

![RocketBoxErrors](https://user-images.githubusercontent.com/57731875/81327713-8e746e80-9050-11ea-9de5-b004aca66834.jpeg)

**Comment by margonzalezfranco** [comment]
Hi Cindy. I don’t understand well your concern. Did you install the import tool on the editor folder? Please send me an email to margon@microsoft.com and we can talk a bit more about how to solve your problem.
