### ISSUE TITLE
Documentation - ModelImporterAnimationType

### ISSUE THREAD

**Issue by dave2ma** [microsoft/Microsoft-Rocketbox#10]
Hello, 

Thank you for providing this great package! I just wanted to let you know that it might be helpful to mention in the documentation / read.me that the attached script "FixRocketboxMaxImport.cs" overwrites the ModelImporterAnimationType (L62). This leads to the fact that you cannot manually select "Humanoid" in the ImportSettings of an avatar.fbx in Unity. A brief note on this would certainly have saved me some time and prevented some confusion. 

Many thanks and best regards
David

**Comment by margonzalezfranco** [comment]
Will do!
Also you can change the importer file to re-configure as humanoid if needed.
Mar

Dr. Mar Gonzalez Franco
margon@microsoft.com
http://research.microsoft.com/people/margon
Microsoft Research, One Microsoft Way, Redmond, WA 98052, USA
Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
