### ISSUE TITLE
Problems with FixRocketBoxMaxImport.cs

### ISSUE THREAD

**Issue by cfortney92** [microsoft/Microsoft-Rocketbox#11]
![image](https://user-images.githubusercontent.com/17227569/110550832-63402d00-8102-11eb-9c03-623f7a923cb7.png)
I'm having this issue - I placed the .cs file under Assets/Editor and edited it from Generic to Humanoid. This allowed me to set the avatar as humanoid, however it has a bunch of Max related errors and the hair and textures are not working correctly.

**Comment by margonzalezfranco** [comment]
Hi Chris,
In general we don’t recommend moving to humanoid. As the facial bones sometimes get messed up. And also reduces compatibility with further libraries such as the MoveBox.

However the textures should not be facing issues related to moving the skeleton type to humanoid.
Send me an email to margon@microsoft.com and we can have a look

Dr. Mar Gonzalez Franco
margon@microsoft.com
http://research.microsoft.com/people/margon
Microsoft Research, One Microsoft Way, Redmond, WA 98052, USA
Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by margonzalezfranco** [comment]
To make this easier I have prepared a short video on how to work this around.



https://youtu.be/gqJTjuyNfh8



Basically you need to make some edits on the Importer file, and comment the parent re-assignation of thighs, and clavicle

I will make a short change on the code with a boolean so it is actually easier for future users.


Dr. Mar Gonzalez Franco
margon@microsoft.com
http://research.microsoft.com/people/margon
Microsoft Research, One Microsoft Way, Redmond, WA 98052, USA
Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
