### ISSUE TITLE
Lipsync in Unity

### ISSUE THREAD

**Issue by Jxlle** [microsoft/Microsoft-Rocketbox#14]
Hello!

Is it possible to implement live lipsync on these models using just the bones in Unity? I saw that the models don't have blendshapes at all so I was curious if this was possible.

Regards

**Comment by TedSwanseaUni** [comment]
Hi, the latest version now has blendshapes you can use for lip-sync.

**Comment by Jxlle** [comment]
@TedSwanseaUni  Thanks!
