### ISSUE TITLE
Skeleton Structure

### ISSUE THREAD

**Issue by Shreeshail-Hingane** [microsoft/Microsoft-Rocketbox#15]
The RocketBox paper mentions that the avatars have 53 body bones and 28 facial bones. Where can I find the list of the names of all the bones and a figure to map these bone-names to their location?
I require this to map the pose data from a video to the RocketBox avatars. I am aware the [MoveBox](https://github.com/microsoft/MoveBox-for-Microsoft-Rocketbox) repository provides this functionality for the VIBE pose detection algorithm. 
I am planning on using a different pose detection method (ex: MediaPipe [Pose](https://google.github.io/mediapipe/solutions/pose.html)) and hence, would need the skeleton structure of RocketBox avatars.
Thanks.

**Comment by margonzalezfranco** [comment]
The easiest way to see the whole hierarchy is opening one of the fbx files and there you have all the names for all the bones

You can also glimpse the naming convention in the script that does the remapping inside Movebox
https://github.com/microsoft/MoveBox-for-Microsoft-Rocketbox/blob/master/MoveBox_CaptureStudio/Assets/Microsoft%20Rocketbox%20MoveBox/Scripts/Skeleton/KinectMoCapRocketboxAvatar.cs

Dr. Mar Gonzalez Franco
***@***.***
http://research.microsoft.com/people/margon
Microsoft Research, One Microsoft Way, Redmond, WA 98052, USA
Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________
From: Shreeshail-Hingane ***@***.***>
Sent: Monday, February 21, 2022 2:23:08 AM
To: microsoft/Microsoft-Rocketbox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/Microsoft-Rocketbox] Skeleton Structure (Issue #15)


The RocketBox paper mentions that the avatars have 53 body bones and 28 facial bones. Where can I find the list of the names of all the bones and a figure to map these bone-names to their location?
I require this to map the pose data from a video to the RocketBox avatars. I am aware the MoveBox<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FMoveBox-for-Microsoft-Rocketbox&data=04%7C01%7Cmargon%40microsoft.com%7C6728f105976c40db728f08d9f5242864%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637810357920412532%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AzRASh6UqYncoI8cOv2pTupJG2KclBRspeCSwY2d8Vo%3D&reserved=0> repository provides this functionality for the VIBE pose detection algorithm.
I am planning on using a different pose detection method (ex: MediaPipe Pose<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgoogle.github.io%2Fmediapipe%2Fsolutions%2Fpose.html&data=04%7C01%7Cmargon%40microsoft.com%7C6728f105976c40db728f08d9f5242864%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637810357920412532%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4u3iUXumi7lJv508JqVCUKRZQ5ZfgxuSD%2B8d0i5YZ4U%3D&reserved=0>) and hence, would need the skeleton structure of RocketBox avatars.
Thanks.
