### ISSUE TITLE
Some file names are inconsistent

### ISSUE THREAD

**Issue by dniku** [microsoft/Microsoft-Rocketbox#4]
* https://github.com/microsoft/Microsoft-Rocketbox/blob/8046857/Assets/Avatars/Adults/Female_Adult_10/Export/Female_Adult_01.fbx should be `Female_Adult_10.fbx`.
* https://github.com/microsoft/Microsoft-Rocketbox/blob/8046857/Assets/Avatars/Professions/Security_Male_02/Export/Security_Male_01.fbx should be `Security_Male_02.fbx`

**Comment by margonzalezfranco** [comment]
Hi! thanks for the heads up,
I have fixed the inconsistencies in the last commit.
Renamed to Female_Adult_10.fbx
And Renamed the whole folder to Security_Male_01
Please let me know if you find further issues!
thanks
