### ISSUE TITLE
T-pose issues Vicon Pegasus

### ISSUE THREAD

**Issue by irisWillaert** [microsoft/Microsoft-Rocketbox#9]
Hi,

I'm very interested in using some of your avatars for my research project. I'd like to use them in Unity and Vicon Pegasus, however, within Vicon Pegasus the characters are not in a T-pose which causes issues when I want to align the Vicon objects with the avatar (see 2 photos: Imported avatar in Pegasus).  The avatar's arms and shoulders are all crushed when I stream the data in Unity as I had to change the position of the avatar in Pegasus to better align the avatar towards the Vicon objects (see photo: Avatar in Unity). 

Would it be possible to change the skeleton of the avatars in T-pose by default? So I can import them in Pegasus and Unity to avoid this issue. I've tried it myself by changing the skeleton in Maya before importing them in Pegasus and use that also in Unity but that didn't solve the issue. 

Appreciate you're help

Many thanks,
Iris

![Avatar in Unity driven by Pegasus animation](https://user-images.githubusercontent.com/66328066/104620800-64526200-565d-11eb-8699-914a02258165.png)
![Imported Avatar in Pegasus -45 degrees arms](https://user-images.githubusercontent.com/66328066/104620804-64526200-565d-11eb-96d8-0f79a25cca94.png)
![Imported Avatar in Pegasus -Manually change arm position to T-pose](https://user-images.githubusercontent.com/66328066/104620805-64eaf880-565d-11eb-9b72-4cb0e3811e33.png)

**Comment by margonzalezfranco** [comment]
Hi Iris,
The best way to fix this is to fix the arm transform on import with this script https://github.com/microsoft/Microsoft-Rocketbox/blob/master/Assets/Editor/FixRocketboxMaxImport.cs

If you see in line 56 you can set Lclavicle and R clavicle rotation



        RClavicle.rotation = new Quaternion(0, -0.6925546f, 0.721365f, 0);
        LClavicle.Find("Bip01 L UpperArm").rotation = new Quaternion(0, 0, 0, 0);
        RClavicle.Find("Bip01 R UpperArm").rotation = new Quaternion(0, 0, 0, 0);




Let me know if playing with this doesn’t fix it


Dr. Mar Gonzalez Franco
margon@microsoft.com
http://research.microsoft.com/people/margon
Microsoft Research, One Microsoft Way, Redmond, WA 98052, USA
Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by irisWillaert** [comment]
Thanks for getting back to me.

unfortunately that did not fix the issue for me. I think the issues lies with the mesh. I can change the skeleton to a t-pose but the mesh did not change. Any ideas how I can change the mesh aswel? 

Thanks a lot,
Iris
![Mesh issue](https://user-images.githubusercontent.com/66328066/104968144-1027e480-59b3-11eb-98db-de93c25384de.png)

**Comment by margonzalezfranco** [comment]
Can you please send me an email and we can schedule a work session to find out a work around?

Dr. Mar Gonzalez Franco
margon@microsoft.com
http://research.microsoft.com/people/margon
Microsoft Research, One Microsoft Way, Redmond, WA 98052, USA
Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by margonzalezfranco** [comment]
We found two ways to solve this:
1. commenting the parent changes on the importer file
pelvis.Find("Bip01 Spine").Find("Bip01 L Thigh").parent = pelvis;
pelvis.Find("Bip01 Spine").Find("Bip01 R Thigh").parent = pelvis;
LClavicle.parent = spine2;
RClavicle.parent = spine2;
This solution might introduce future incompatibilities for example with the movebox toolbox. That will ofcourse be fixable but will require some implementation

2.re-exporting the avatar as an fbx after the import. This ensures that the hierarchy and the t-pose enforced by the importer file are persistent and Pegasus can be trained with that. So the correspondence works.
This solution introduces 2 issues, this would need to be done for each avatar, and also the unity personal license does not allow for fbx exports.
